docs_dir: doc/book/ru
pages:
    - index.md
site_name: workflow-zf2-toolkit
site_description: 'Набор утилит и сервисов для работы с workflow,zf2,doctrine'
repo_url: ' https://github.com/old-town/workflow-zf2-toolkit'
copyright: 'Copyright (c) 2016 <a href="https://github.com/old-town/">OldTown</a>'